services:
  coordinator:
    build:
      context: "."
      dockerfile: "coordinator.dockerfile"
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "docker.io/postgres:16-alpine"
    environment:
      POSTGRES_USER: administrator
      POSTGRES_DB: dm
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U administrator -d dm"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
  