services:
  coordinator:
    build:
      context: "."
      dockerfile: "coordinator.dockerfile"

  postgres:
    image: "docker.io/postgres:16"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: